<a href="https://colab.research.google.com/github/Vivek-Sajjan/Conversational-AI-Project/blob/main/twitter_analysis_Apple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import pandas as pd

In [42]:
df = pd.read_csv('/content/AppleSupport_tweets.csv')
display(df.head())

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,696,AppleSupport,False,Tue Oct 31 22:27:49 +0000 2017,@115854 We're here for you. Which version of t...,697,698.0
1,697,115854,True,Tue Oct 31 22:31:23 +0000 2017,@AppleSupport The newest update. I️ made sure ...,699,696.0
2,699,AppleSupport,False,Tue Oct 31 22:36:27 +0000 2017,@115854 Lets take a closer look into this issu...,NaN,697.0
3,698,115854,True,Tue Oct 31 22:17:40 +0000 2017,@AppleSupport https://t.co/NV0yucs0lB,696,700.0
4,700,115854,True,Tue Oct 31 22:16:56 +0000 2017,@AppleSupport why are my I️’s changing not sho...,698,NaN

In [43]:
df.shape

(65824, 7)

In [45]:
# Create a new 'role' column based on the 'inbound' column
df['role'] = df['inbound'].apply(lambda x: 'Customer' if x else 'Service Provider')

# Get the list of existing columns
cols = df.columns.tolist()

# Move the 'role' column to the second position (index 2)
cols.insert(2, cols.pop(cols.index('role')))

# Reindex the DataFrame with the new column order
df = df[cols]

# Display the head of the modified DataFrame
display(df.head(2))

,tweet_id,author_id,role,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,696,AppleSupport,Service Provider,False,Tue Oct 31 22:27:49 +0000 2017,@115854 We're here for you. Which version of t...,697,698.0
1,697,115854,Customer,True,Tue Oct 31 22:31:23 +0000 2017,@AppleSupport The newest update. I️ made sure ...,699,696.0

In [46]:
# Convert 'created_at' to datetime objects
df['created_at'] = pd.to_datetime(df['created_at'], errors='coerce')

# Extract date and time into new columns
df['created_date'] = df['created_at'].dt.date
df['created_time'] = df['created_at'].dt.time

/tmp/ipython-input-4225294526.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['created_at'] = pd.to_datetime(df['created_at'], errors='coerce')

In [47]:
df.head(2)

,tweet_id,author_id,role,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id,created_date,created_time
0,696,AppleSupport,Service Provider,False,2017-10-31 22:27:49+00:00,@115854 We're here for you. Which version of t...,697,698.0,2017-10-31,22:27:49
1,697,115854,Customer,True,2017-10-31 22:31:23+00:00,@AppleSupport The newest update. I️ made sure ...,699,696.0,2017-10-31,22:31:23

In [48]:
df=df.drop('created_at',axis=1)

In [49]:
# Get the list of existing columns
cols = df.columns.tolist()

# Remove 'created_at' if it exists
if 'created_at' in cols:
    cols.remove('created_at')

# Create a new list of columns with 'created_date' and 'created_time' at the desired position
# This approach ensures that 'created_date' and 'created_time' are inserted only once
new_cols = cols[:4] + ['created_date', 'created_time'] + cols[4:]

# Reindex the DataFrame with the new column order, dropping any duplicate columns in the process
df = df[new_cols].loc[:,~df[new_cols].columns.duplicated()]


# Display the head of the modified DataFrame
display(df.head())

,tweet_id,author_id,role,inbound,created_date,created_time,text,response_tweet_id,in_response_to_tweet_id
0,696,AppleSupport,Service Provider,False,2017-10-31,22:27:49,@115854 We're here for you. Which version of t...,697,698.0
1,697,115854,Customer,True,2017-10-31,22:31:23,@AppleSupport The newest update. I️ made sure ...,699,696.0
2,699,AppleSupport,Service Provider,False,2017-10-31,22:36:27,@115854 Lets take a closer look into this issu...,NaN,697.0
3,698,115854,Customer,True,2017-10-31,22:17:40,@AppleSupport https://t.co/NV0yucs0lB,696,700.0
4,700,115854,Customer,True,2017-10-31,22:16:56,@AppleSupport why are my I️’s changing not sho...,698,NaN

In [50]:
from datetime import datetime

# Ensure 'created_date' is in datetime format
df['created_date'] = pd.to_datetime(df['created_date'], errors='coerce')

In [51]:
# Convert 'created_time' to datetime objects and then format as 24-hour time string
df['created_time'] = pd.to_datetime(df['created_time'], format='%I:%M:%S %p').dt.strftime('%H:%M:%S')

# Display the head of the DataFrame to show the modified 'created_time' column
display(df.head())

ValueError: time data "22:27:49" doesn't match format "%I:%M:%S %p", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [52]:
# Rename the column
df = df.rename(columns={'created_date': 'created_at'})

# Display the head of the DataFrame to show the renamed column
display(df.head())

,tweet_id,author_id,role,inbound,created_at,created_time,text,response_tweet_id,in_response_to_tweet_id
0,696,AppleSupport,Service Provider,False,2017-10-31,22:27:49,@115854 We're here for you. Which version of t...,697,698.0
1,697,115854,Customer,True,2017-10-31,22:31:23,@AppleSupport The newest update. I️ made sure ...,699,696.0
2,699,AppleSupport,Service Provider,False,2017-10-31,22:36:27,@115854 Lets take a closer look into this issu...,NaN,697.0
3,698,115854,Customer,True,2017-10-31,22:17:40,@AppleSupport https://t.co/NV0yucs0lB,696,700.0
4,700,115854,Customer,True,2017-10-31,22:16:56,@AppleSupport why are my I️’s changing not sho...,698,NaN

# Task
Analyze the file and build the conversations.

## Identify conversation starters

### Subtask:
Find the initial tweets that start a conversation (those with no `in_response_to_tweet_id`).

**Reasoning**:
Filter the dataframe to find tweets with no response, which signify the start of a conversation. Store the results in a new dataframe and display the head.

In [53]:
conversation_starters_df = df[df['in_response_to_tweet_id'].isnull()]
display(conversation_starters_df.head())

,tweet_id,author_id,role,inbound,created_at,created_time,text,response_tweet_id,in_response_to_tweet_id
4,700,115854,Customer,True,2017-10-31,22:16:56,@AppleSupport why are my I️’s changing not sho...,698,NaN
15,714,115856,Customer,True,2017-10-31,22:19:32,Hey @AppleSupport and anyone else who upgraded...,"7,12,715",NaN
22,723,115859,Customer,True,2017-10-31,22:11:16,@115858 @AppleSupport hello are all the lines ...,722,NaN
28,730,115861,Customer,True,2017-10-31,20:46:35,"Hello, internet. Can someone explain why this ...","7,29,731",NaN
30,733,115863,Customer,True,2017-10-31,22:16:40,@AppleSupport I’ve got a screenshot saying my ...,732,NaN

In [54]:
conversation_starters_df.shape

(15821, 9)

## Trace conversations

### Subtask:
For the first few conversation starters, trace the subsequent tweets using `tweet_id`, `response_tweet_id`, and `in_response_to_tweet_id` to build complete conversation threads.

**Reasoning**:
Iterate through the all the conversation starters and trace their replies to build complete conversation threads.

In [55]:
conversations = []
for index, starter_tweet in conversation_starters_df.iterrows():
    conversation = [starter_tweet]
    current_tweet_id = starter_tweet['tweet_id']

    while True:
        next_tweet = df[df['in_response_to_tweet_id'] == current_tweet_id]
        if not next_tweet.empty:
            # Assuming there's only one reply per tweet in a simple thread
            current_tweet = next_tweet.iloc[0]
            conversation.append(current_tweet)
            current_tweet_id = current_tweet['tweet_id']
        else:
            break
    conversations.append(conversation)

# Display the first conversation as an example
if conversations:
    print("First Conversation Thread:")
    for tweet in conversations[0]:
        display(tweet)

First Conversation Thread:

tweet_id                                                                 700
author_id                                                             115854
role                                                                Customer
inbound                                                                 True
created_at                                               2017-10-31 00:00:00
created_time                                                        22:16:56
text                       @AppleSupport why are my I️’s changing not sho...
response_tweet_id                                                        698
in_response_to_tweet_id                                                  NaN
Name: 4, dtype: object

tweet_id                                                      698
author_id                                                  115854
role                                                     Customer
inbound                                                      True
created_at                                    2017-10-31 00:00:00
created_time                                             22:17:40
text                       @AppleSupport  https://t.co/NV0yucs0lB
response_tweet_id                                             696
in_response_to_tweet_id                                     700.0
Name: 3, dtype: object

tweet_id                                                                 696
author_id                                                       AppleSupport
role                                                        Service Provider
inbound                                                                False
created_at                                               2017-10-31 00:00:00
created_time                                                        22:27:49
text                       @115854 We're here for you. Which version of t...
response_tweet_id                                                        697
in_response_to_tweet_id                                                698.0
Name: 0, dtype: object

tweet_id                                                                 697
author_id                                                             115854
role                                                                Customer
inbound                                                                 True
created_at                                               2017-10-31 00:00:00
created_time                                                        22:31:23
text                       @AppleSupport The newest update. I️ made sure ...
response_tweet_id                                                        699
in_response_to_tweet_id                                                696.0
Name: 1, dtype: object

tweet_id                                                                 699
author_id                                                       AppleSupport
role                                                        Service Provider
inbound                                                                False
created_at                                               2017-10-31 00:00:00
created_time                                                        22:36:27
text                       @115854 Lets take a closer look into this issu...
response_tweet_id                                                        NaN
in_response_to_tweet_id                                                697.0
Name: 2, dtype: object

In [56]:
# Ensure 'created_at' is in datetime format
df['created_at'] = pd.to_datetime(df['created_at'])

# Extract the year from 'created_at' and group by year
grouped_by_year = df.groupby(df['created_at'].dt.year).size().reset_index(name='count')

# Rename the columns for clarity
grouped_by_year.columns = ['year', 'message_count']

# Display the result
display(grouped_by_year)

   year  message_count
0  2016              3
1  2017          65821

In [57]:
# Ensure 'created_at' is in datetime format
df['created_at'] = pd.to_datetime(df['created_at'])

# Extract the month from 'created_at' and group by month
grouped_by_month = df.groupby(df['created_at'].dt.month).size().reset_index(name='count')

# Rename the columns for clarity
grouped_by_month.columns = ['month', 'message_count']

# Display the result
display(grouped_by_month)

    month  message_count
0       1              7
1       2              6
2       3              8
3       4             12
4       5              5
5       6              1
6       7              1
7       8              7
8       9            224
9      10          41188
10     11          14922
11     12           9443

## Structure the conversations

### Subtask:
Organize the identified tweets into the distinct conversation structures.

**Reasoning**:
Create a list to store the structured conversations and iterate through the traced conversations to organize them into a structured format.

In [59]:
import json
import numpy as np
from datetime import datetime, time # Import time as well
import pandas as pd # Import pandas

# Custom encoder to handle NumPy types, including booleans and datetime
class NpEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, np.bool_):
            return bool(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        # Add handling for pandas Series to convert them to dictionary
        if isinstance(obj, pd.Series):
            return obj.to_dict()
        # Add handling for pandas Timestamp objects
        if isinstance(obj, pd.Timestamp):
            return obj.isoformat() # Convert Timestamp to ISO 8601 string
        # Add handling for datetime objects
        if isinstance(obj, datetime):
            return obj.isoformat() # Convert datetime to ISO 8601 string
        # Handle time objects
        if isinstance(obj, time): # Use the imported time object
            return obj.isoformat()
        return super(NpEncoder, self).default(obj)

structured_conversations = []

for i, conversation_thread in enumerate(conversations):  # Process all conversations
    structured_thread = {
        'conversation_number': i + 1,
        'customer': 'Apple',
        'tweets': []
    }
    for tweet in conversation_thread:
        structured_thread['tweets'].append({
            'tweet_id': tweet['tweet_id'],
            'author_id': tweet['author_id'],
            'role': tweet['role'],
            'inbound': tweet['inbound'],
            'created_at': tweet['created_at'],
            'created_time': tweet['created_time'], # Include created_time
            'text': tweet['text']
        })
    structured_conversations.append(structured_thread)

# Display the first structured conversation as an example
if structured_conversations:
    print("First Structured Conversation:")
    # Print the dictionary representation for clarity
    print(json.dumps(structured_conversations[0], indent=4, cls=NpEncoder))

First Structured Conversation:
{
    "conversation_number": 1,
    "customer": "Apple",
    "tweets": [
        {
            "tweet_id": 700,
            "author_id": "115854",
            "role": "Customer",
            "inbound": true,
            "created_at": "2017-10-31T00:00:00",
            "created_time": "22:16:56",
            "text": "@AppleSupport why are my I\ufe0f\u2019s changing not showing up correctly on any of my social media platforms? https://t.co/GyRvpyVnkE"
        },
        {
            "tweet_id": 698,
            "author_id": "115854",
            "role": "Customer",
            "inbound": true,
            "created_at": "2017-10-31T00:00:00",
            "created_time": "22:17:40",
            "text": "@AppleSupport  https://t.co/NV0yucs0lB"
        },
        {
            "tweet_id": 696,
            "author_id": "AppleSupport",
            "role": "Service Provider",
            "inbound": false,
            "created_at": "2017-10-31T00:00:00",
            "created_time": "22:27:49",
            "text": "@115854 We're here for you. Which version of the iOS are you running? Check from Settings &gt; General &gt; About."
        },
        {
            "tweet_id": 697,
            "author_id": "115854",
            "role": "Customer",
            "inbound": true,
            "created_at": "2017-10-31T00:00:00",
            "created_time": "22:31:23",
            "text": "@AppleSupport The newest update. I\ufe0f made sure to download it yesterday."
        },
        {
            "tweet_id": 699,
            "author_id": "AppleSupport",
            "role": "Service Provider",
            "inbound": false,
            "created_at": "2017-10-31T00:00:00",
            "created_time": "22:36:27",
            "text": "@115854 Lets take a closer look into this issue. Select the following link to join us in a DM and we'll go from there. https://t.co/GDrqU22YpT"
        }
    ]
}

In [ ]:
!pip install pytz

Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (2025.2)

In [60]:
import random
import json
import numpy as np
from datetime import datetime, time # Import time as well
import pytz
import pandas as pd # Import pandas

# Get current time in Indian Standard Time (IST)
ist = pytz.timezone('Asia/Kolkata')
current_time_ist = datetime.now(ist)

# Generate filename with current date and time (IST) in requested format
formatted_time = current_time_ist.strftime('%Y%m%d_%H%M%S')
output_filename = f'Apple_100_Nov2017_{formatted_time}.json'


# Custom encoder to handle NumPy types, including booleans and datetime
class NpEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, np.bool_):
            return bool(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        # Add handling for pandas Series to convert them to dictionary
        if isinstance(obj, pd.Series):
            return obj.to_dict()
        # Add handling for datetime objects (including pandas Timestamp which is a subclass)
        if isinstance(obj, (datetime, pd.Timestamp)):
            return obj.isoformat() # Convert datetime/Timestamp to ISO 8601 string
        # Handle time objects
        if isinstance(obj, time): # Use the imported time object
            return obj.isoformat()
        return super(NpEncoder, self).default(obj)


# Filter conversations for November 2017
nov_2017_conversations = []
for conversation in structured_conversations:
    # Check if any tweet in the conversation is from Nov 2017
    if any(isinstance(tweet['created_at'], (datetime, pd.Timestamp)) and
           tweet['created_at'].year == 2017 and
           tweet['created_at'].month == 11
           for tweet in conversation['tweets']):
        nov_2017_conversations.append(conversation)


# Select 100 random conversations from the filtered list
if len(nov_2017_conversations) >= 100:
    random_nov_2017_conversations = random.sample(nov_2017_conversations, 100)
else:
    random_nov_2017_conversations = nov_2017_conversations
    print(f"Warning: Only {len(nov_2017_conversations)} conversations found for November 2017. Saving all of them.")


# Save the selected conversations to a JSON file
with open(output_filename, 'w') as f:
    json.dump(random_nov_2017_conversations, f, indent=4, cls=NpEncoder)

print(f"Selected {len(random_nov_2017_conversations)} random conversations from November 2017 saved to '{output_filename}'")

Selected 100 random conversations from November 2017 saved to 'Apple_100_Nov2017_20251001_123911.json'