<a href="https://colab.research.google.com/github/Vivek-Sajjan/Conversational-AI-Project/blob/main/twitter_analysis_uber.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/Uber_Support_tweets.csv')
display(df.head())

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,768,Uber_Support,False,Tue Oct 31 22:28:17 +0000 2017,@115872 Happy to follow up! Contact us via htt...,"7,69,770",771.0
1,769,115872,True,Tue Oct 31 22:30:07 +0000 2017,@Uber_Support Already did that was told we req...,NaN,768.0
2,770,Uber_Support,False,Tue Oct 31 22:31:08 +0000 2017,@115872 We apologize for the trouble! Send us ...,NaN,768.0
3,772,Uber_Support,False,Tue Oct 31 22:25:26 +0000 2017,@115874 We're here to help! Send us a note her...,NaN,773.0
4,774,Uber_Support,False,Tue Oct 31 22:19:18 +0000 2017,"@115875 We’re here to help, Travis! Send us a ...",NaN,775.0

In [4]:
df.shape

(39502, 7)

In [5]:
# Create a new 'role' column based on the 'inbound' column
df['role'] = df['inbound'].apply(lambda x: 'Customer' if x else 'Service Provider')

# Get the list of existing columns
cols = df.columns.tolist()

# Move the 'role' column to the second position (index 2)
cols.insert(2, cols.pop(cols.index('role')))

# Reindex the DataFrame with the new column order
df = df[cols]

# Display the head of the modified DataFrame
display(df.head())

,tweet_id,author_id,role,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,768,Uber_Support,Service Provider,False,Tue Oct 31 22:28:17 +0000 2017,@115872 Happy to follow up! Contact us via htt...,"7,69,770",771.0
1,769,115872,Customer,True,Tue Oct 31 22:30:07 +0000 2017,@Uber_Support Already did that was told we req...,NaN,768.0
2,770,Uber_Support,Service Provider,False,Tue Oct 31 22:31:08 +0000 2017,@115872 We apologize for the trouble! Send us ...,NaN,768.0
3,772,Uber_Support,Service Provider,False,Tue Oct 31 22:25:26 +0000 2017,@115874 We're here to help! Send us a note her...,NaN,773.0
4,774,Uber_Support,Service Provider,False,Tue Oct 31 22:19:18 +0000 2017,"@115875 We’re here to help, Travis! Send us a ...",NaN,775.0

In [6]:
# Convert 'created_at' to datetime objects
df['created_at'] = pd.to_datetime(df['created_at'], errors='coerce')

# Extract date and time into new columns
df['created_date'] = df['created_at'].dt.date
df['created_time'] = df['created_at'].dt.time

/tmp/ipython-input-4225294526.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['created_at'] = pd.to_datetime(df['created_at'], errors='coerce')

In [8]:
df=df.drop('created_at',axis=1)

In [14]:
# Get the list of existing columns
cols = df.columns.tolist()

# Remove 'created_at' if it exists
if 'created_at' in cols:
    cols.remove('created_at')

# Create a new list of columns with 'created_date' and 'created_time' at the desired position
# This approach ensures that 'created_date' and 'created_time' are inserted only once
new_cols = cols[:4] + ['created_date', 'created_time'] + cols[4:]

# Reindex the DataFrame with the new column order, dropping any duplicate columns in the process
df = df[new_cols].loc[:,~df[new_cols].columns.duplicated()]


# Display the head of the modified DataFrame
display(df.head())

,tweet_id,author_id,role,inbound,created_date,created_time,text,response_tweet_id,in_response_to_tweet_id
0,768,Uber_Support,Service Provider,False,2017-10-31,22:28:17,@115872 Happy to follow up! Contact us via htt...,"7,69,770",771.0
1,769,115872,Customer,True,2017-10-31,22:30:07,@Uber_Support Already did that was told we req...,NaN,768.0
2,770,Uber_Support,Service Provider,False,2017-10-31,22:31:08,@115872 We apologize for the trouble! Send us ...,NaN,768.0
3,772,Uber_Support,Service Provider,False,2017-10-31,22:25:26,@115874 We're here to help! Send us a note her...,NaN,773.0
4,774,Uber_Support,Service Provider,False,2017-10-31,22:19:18,"@115875 We’re here to help, Travis! Send us a ...",NaN,775.0

In [15]:
from datetime import datetime

# Ensure 'created_date' is in datetime format
df['created_date'] = pd.to_datetime(df['created_date'], errors='coerce')

In [30]:
# Convert 'created_time' to datetime objects and then format as 24-hour time string
df['created_time'] = pd.to_datetime(df['created_time'], format='%I:%M:%S %p').dt.strftime('%H:%M:%S')

# Display the head of the DataFrame to show the modified 'created_time' column
display(df.head())

,tweet_id,author_id,role,inbound,created_at,created_time,text,response_tweet_id,in_response_to_tweet_id
0,768,Uber_Support,Service Provider,False,2017-10-31,22:28:17,@115872 Happy to follow up! Contact us via htt...,"7,69,770",771.0
1,769,115872,Customer,True,2017-10-31,22:30:07,@Uber_Support Already did that was told we req...,NaN,768.0
2,770,Uber_Support,Service Provider,False,2017-10-31,22:31:08,@115872 We apologize for the trouble! Send us ...,NaN,768.0
3,772,Uber_Support,Service Provider,False,2017-10-31,22:25:26,@115874 We're here to help! Send us a note her...,NaN,773.0
4,774,Uber_Support,Service Provider,False,2017-10-31,22:19:18,"@115875 We’re here to help, Travis! Send us a ...",NaN,775.0

In [16]:
# Rename the column
df = df.rename(columns={'created_date': 'created_at'})

# Display the head of the DataFrame to show the renamed column
display(df.head())

,tweet_id,author_id,role,inbound,created_at,created_time,text,response_tweet_id,in_response_to_tweet_id
0,768,Uber_Support,Service Provider,False,2017-10-31,22:28:17,@115872 Happy to follow up! Contact us via htt...,"7,69,770",771.0
1,769,115872,Customer,True,2017-10-31,22:30:07,@Uber_Support Already did that was told we req...,NaN,768.0
2,770,Uber_Support,Service Provider,False,2017-10-31,22:31:08,@115872 We apologize for the trouble! Send us ...,NaN,768.0
3,772,Uber_Support,Service Provider,False,2017-10-31,22:25:26,@115874 We're here to help! Send us a note her...,NaN,773.0
4,774,Uber_Support,Service Provider,False,2017-10-31,22:19:18,"@115875 We’re here to help, Travis! Send us a ...",NaN,775.0

# Task
Analyze the "Delta_Airline" file and build the conversations.

## Identify conversation starters

### Subtask:
Find the initial tweets that start a conversation (those with no `in_response_to_tweet_id`).

**Reasoning**:
Filter the dataframe to find tweets with no response, which signify the start of a conversation. Store the results in a new dataframe and display the head.

In [17]:
conversation_starters_df = df[df['in_response_to_tweet_id'].isnull()]
display(conversation_starters_df.head())

,tweet_id,author_id,role,inbound,created_at,created_time,text,response_tweet_id,in_response_to_tweet_id
5,775,115875,Customer,True,2017-10-31,21:59:51,@Uber_Support I’m not getting your texts. http...,774,NaN
11,782,115878,Customer,True,2017-10-31,21:40:20,Literally stranded because of @115873 and beca...,781,NaN
23,1803,116111,Customer,True,2017-10-31,22:19:10,Bruh can someone at @115873 @Uber_Support get ...,1801,NaN
25,1807,116112,Customer,True,2017-10-31,22:13:49,.@Uber_Support My driver broke down. Any tips ...,1806,NaN
31,1866,116127,Customer,True,2017-12-01,06:44:23,@Uber_Support I have submitted complain agains...,1864,NaN

In [31]:
conversation_starters_df.shape

(7461, 9)

## Trace conversations

### Subtask:
For the first few conversation starters, trace the subsequent tweets using `tweet_id`, `response_tweet_id`, and `in_response_to_tweet_id` to build complete conversation threads.

**Reasoning**:
Iterate through the all the conversation starters and trace their replies to build complete conversation threads.

In [32]:
conversations = []
for index, starter_tweet in conversation_starters_df.iterrows():
    conversation = [starter_tweet]
    current_tweet_id = starter_tweet['tweet_id']

    while True:
        next_tweet = df[df['in_response_to_tweet_id'] == current_tweet_id]
        if not next_tweet.empty:
            # Assuming there's only one reply per tweet in a simple thread
            current_tweet = next_tweet.iloc[0]
            conversation.append(current_tweet)
            current_tweet_id = current_tweet['tweet_id']
        else:
            break
    conversations.append(conversation)

# Display the first conversation as an example
if conversations:
    print("First Conversation Thread:")
    for tweet in conversations[0]:
        display(tweet)

First Conversation Thread:

tweet_id                                                                 775
author_id                                                             115875
role                                                                Customer
inbound                                                                 True
created_at                                               2017-10-31 00:00:00
created_time                                                        21:59:51
text                       @Uber_Support I’m not getting your texts. http...
response_tweet_id                                                        774
in_response_to_tweet_id                                                  NaN
Name: 5, dtype: object

tweet_id                                                                 774
author_id                                                       Uber_Support
role                                                        Service Provider
inbound                                                                False
created_at                                               2017-10-31 00:00:00
created_time                                                        22:19:18
text                       @115875 We’re here to help, Travis! Send us a ...
response_tweet_id                                                        NaN
in_response_to_tweet_id                                                775.0
Name: 4, dtype: object

## Structure the conversations

### Subtask:
Organize the identified tweets into the distinct conversation structures.

**Reasoning**:
Create a list to store the structured conversations and iterate through the traced conversations to organize them into a structured format.

In [38]:
import json
import numpy as np
from datetime import datetime, time # Import time as well
import pandas as pd # Import pandas

# Custom encoder to handle NumPy types, including booleans and datetime
class NpEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, np.bool_):
            return bool(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        # Add handling for pandas Series to convert them to dictionary
        if isinstance(obj, pd.Series):
            return obj.to_dict()
        # Add handling for pandas Timestamp objects
        if isinstance(obj, pd.Timestamp):
            return obj.isoformat() # Convert Timestamp to ISO 8601 string
        # Add handling for datetime objects
        if isinstance(obj, datetime):
            return obj.isoformat() # Convert datetime to ISO 8601 string
        # Handle time objects
        if isinstance(obj, time): # Use the imported time object
            return obj.isoformat()
        return super(NpEncoder, self).default(obj)

structured_conversations = []

for i, conversation_thread in enumerate(conversations):  # Process all conversations
    structured_thread = {
        'conversation_number': i + 1,
        'customer': 'Uber',
        'tweets': []
    }
    for tweet in conversation_thread:
        structured_thread['tweets'].append({
            'tweet_id': tweet['tweet_id'],
            'author_id': tweet['author_id'],
            'role': tweet['role'],
            'inbound': tweet['inbound'],
            'created_at': tweet['created_at'],
            'created_time': tweet['created_time'], # Include created_time
            'text': tweet['text']
        })
    structured_conversations.append(structured_thread)

# Display the first structured conversation as an example
if structured_conversations:
    print("First Structured Conversation:")
    # Print the dictionary representation for clarity
    print(json.dumps(structured_conversations[0], indent=4, cls=NpEncoder))

First Structured Conversation:
{
    "conversation_number": 1,
    "customer": "Uber",
    "tweets": [
        {
            "tweet_id": 775,
            "author_id": "115875",
            "role": "Customer",
            "inbound": true,
            "created_at": "2017-10-31T00:00:00",
            "created_time": "21:59:51",
            "text": "@Uber_Support I\u2019m not getting your texts. https://t.co/GhefNjQTfg"
        },
        {
            "tweet_id": 774,
            "author_id": "Uber_Support",
            "role": "Service Provider",
            "inbound": false,
            "created_at": "2017-10-31T00:00:00",
            "created_time": "22:19:18",
            "text": "@115875 We\u2019re here to help, Travis! Send us a note via https://t.co/dwDjAokZht and we'll be in touch."
        }
    ]
}

In [ ]:
!pip install pytz

Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (2025.2)

In [40]:
import random
import json
import numpy as np
from datetime import datetime, time # Import time as well
import pytz
import pandas as pd # Import pandas

# Get current time in Indian Standard Time (IST)
ist = pytz.timezone('Asia/Kolkata')
current_time_ist = datetime.now(ist)

# Generate filename with current date and time (IST) in requested format
formatted_time = current_time_ist.strftime('%Y%m%d_%H%M%S')
output_filename = f'Uber_100_Oct2017_{formatted_time}.json'


# Custom encoder to handle NumPy types, including booleans and datetime
class NpEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, np.bool_):
            return bool(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        # Add handling for pandas Series to convert them to dictionary
        if isinstance(obj, pd.Series):
            return obj.to_dict()
        # Add handling for datetime objects (including pandas Timestamp which is a subclass)
        if isinstance(obj, (datetime, pd.Timestamp)):
            return obj.isoformat() # Convert datetime/Timestamp to ISO 8601 string
        # Handle time objects
        if isinstance(obj, time): # Use the imported time object
            return obj.isoformat()
        return super(NpEncoder, self).default(obj)


# Filter conversations for October 2017
oct_2017_conversations = []
for conversation in structured_conversations:
    # Check if any tweet in the conversation is from Oct 2017
    if any(isinstance(tweet['created_at'], (datetime, pd.Timestamp)) and
           tweet['created_at'].year == 2017 and
           tweet['created_at'].month == 10
           for tweet in conversation['tweets']):
        oct_2017_conversations.append(conversation)


# Select 100 random conversations from the filtered list
if len(oct_2017_conversations) >= 100:
    random_oct_2017_conversations = random.sample(oct_2017_conversations, 100)
else:
    random_oct_2017_conversations = oct_2017_conversations
    print(f"Warning: Only {len(oct_2017_conversations)} conversations found for October 2017. Saving all of them.")


# Save the selected conversations to a JSON file
with open(output_filename, 'w') as f:
    json.dump(random_oct_2017_conversations, f, indent=4, cls=NpEncoder)

print(f"Selected {len(random_oct_2017_conversations)} random conversations from October 2017 saved to '{output_filename}'")

Selected 100 random conversations from October 2017 saved to 'Uber_100_Oct2017_20251001_115441.json'